FROM kalilinux/kali-rolling
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    nmap nikto whatweb wapiti ca-certificates && \
    rm -rf /var/lib/apt/lists/*
CMD ["sleep", "infinity"]
